### PR TITLE
Allow additional sbt tasks to be run before deployment

### PR DESCRIPTION
**Pull request by RohanPrabhuNomadly**
Please close the PR if it does not align with the design goals of this buildpack. If any changes in the documentation would be required to adhere to the format, kindly update.

### CODE REVIEW

**Comment by jkutner** [comment]
I'm fine with the intention of this feature. But how about just allowing `SBT_TASKS` to be overridden instead of the more verbose `SBT_ADDITIONAL_TASKS`? In that way you could set `heroku config:set SBT_TASKS="flyway:migrate info compile stage"` (including the stage). 

Would that work for you? If so, I'll make the change and merge this.

**Comment by jkutner** [comment]
@RohanPrabhuNomadly does ^^ sound ok?

**Comment by RohanPrabhuNomadly** [comment]
I am so sorry I did not reply to this all while. For some reason, I just did not get notified that there was activity on this PR. Yes, this does sound reasonable and makes more sense. I will update the pull request.

**Comment by RohanPrabhuNomadly** [comment]
On a second thought, won't just allowing `SBT_TASKS` to be overwritten cause issues with the release script? Given what I am aware of, I believe the release script and others depend on the `stage` target to be run (so that the running binary is present in `target/universal/stage`). Given that, it does not seem right that while there is a provision to change the build behaviour, there isn't provided a behaviour to alter the release cycle as well that mirrors this functionality.

Which is why, I do think it'd be better to allow adding additional tasks while still maintaining the fact that `stage` will always be run. Kindly give your thoughts on the same.

**Comment by jkutner** [comment]
@RohanPrabhuNomadly yea, that's true. I'm still hung up on the variable name though. What if we change it to `SBT_PRE_TASKS`, which is actually more accurate?

**Comment by RohanPrabhuNomadly** [comment]
That sounds great, and yes, it is accurate. Also enforces that `compile stage` will still be the last targets run, because that must be ensured (to enforce the previous contract, as running a `clean` after that breaks the expectation of `release`).

**Comment by jkutner** [comment]
Thanks for the contribution. You can use this now by setting the Github URL as your buildpack:

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-scala
```

Or you can wait for the release, which will come either later today or early tomorrow.

**Pull request merged**
